problem:
  name: DropletSeperation
  template_case: 'originalCase'
  type: 'parameter_variation'
  models:
    UNIFORM: 4
  parameters:
    l:
      type: range
      value_type: float
      bounds: [0.0005, 0.002]
      log_scale: False
    g:
      type: choice
      value_type: str
      values: ['4.1458 -8.89087', '8.495 -4.905'] # 25 60
      log_scale: False
      is_ordered: True
  scopes:
    "/0.orig/theta0WaterAir":
      l: "l"
    "/constant/g":
      g: "g"
  objectives:
    Bo:
      command: ['pvpython', './trial.py', '--Bo']
      threshold: 5
      minimize: True
      lower_is_better: True
    L:
      command: ['pvpython', './trial.py', '--L']
      threshold: 5
      minimize: True
      lower_is_better: True

meta:
  case_subdirs_to_clone:
    - 0.orig
    - trial.py
    - Allrun.slurm
  clone_destination: "./trials/"
  case_run_mode: slurm
  case_run_command: ['./Allrun', '-p']
  metric_value_mode: 'local'
  n_trials: 4
  n_parallel_trials: 2
  ttl_trial: 3600
  init_poll_wait: 0.1
  poll_factor: 1.5
  timeout: 10
  use_saasbo: False
  n_pareto_points: 5
  stopping_strategy:
    improvement_bar: 1e-4
    min_trials: 300
    window_size: 10

visualize:
  update_interval: 15
  n_latest_trials: 3
  zscore_bar: 15
  host: '0.0.0.0'
  port: 8888
