problem:
  name: Entrapment_0
  template_case: 'originalCase'
  type: 'parameter_variation'
  models:
    UNIFORM: 9
  parameters:
    l:
      type: choice
      value_type: float
      values: ['0.00004501', '0.0004500001', '0.0045000001'] #L/D0= 0.01, 0.1, 1
      log_scale: False
      is_ordered: True
    g:
      type: choice
      value_type: str
      values: ['4.14589 -8.8908', '7.51491 -6.305741', '9.47571 -2.53902'] # alpha = 25 50 75
      log_scale: False
      is_ordered: True
  scopes:
    "/0.orig/theta0WaterAir":
      l: "l"
    "/constant/g":
      g: "g"
  objectives:
    We:
      mode: 'shell'
      command: ['pvpython', './trial.py', '--We']
      threshold: 5
      minimize: True
      lower_is_better: True      
    Bo:
      mode: 'shell'
      prepare: ['echo', '$CASE_NAME']
      command: ['pvpython', './trial.py', '--Bo']
      threshold: 5
      minimize: True
      lower_is_better: True
    L:
      mode: 'shell'
      command: ['pvpython', './trial.py', '--L']
      threshold: 5
      minimize: True
      lower_is_better: True
    i:
      mode: 'shell'
      command: ['pvpython', './trial.py', '--i']
      threshold: 5
      minimize: True
      lower_is_better: True
    n:
      mode: 'shell'
      command: ['pvpython', './trial.py', '--n']
      threshold: 5
      minimize: True
      lower_is_better: True

meta:
  case_subdirs_to_clone:
    - 0.orig
    - trial.py
    - Allrun
    - Allclean
    - Allrun.slurm
  clone_destination: "./trials/"
  case_run_mode: slurm
  case_run_command: ['sbatch', '-J', '$CASE_NAME', './Allrun.slurm', '$CASE_PATH' ]
  metric_value_mode: 'local'
  slurm_status_query: ['sacct', '--name', '$CASE_NAME', '-o', 'JobName%60,State', '-n']
  init_poll_wait: 300
  n_trials: 9
  n_parallel_trials: 2
  poll_factor: 1.5
  timeout: 10
  use_saasbo: False
  n_pareto_points: 5
  stopping_strategy:
    improvement_bar: 1e-4
    min_trials: 300
    window_size: 10

# visualize:
#   update_interval: 15
#   n_latest_trials: 3
#   zscore_bar: 15
#   host: '0.0.0.0'
#   port: 8888
